In [1]:
import sqlite3
import pandas as pd

In [2]:
# Create / connect to SQLite database
conn = sqlite3.connect("my_database.db")

print("Database created and connected successfully")

Database created and connected successfully

In [3]:
import os

os.getcwd()

"C:\\Users\\mayan\\Ethan's Python classes"

In [4]:
os.listdir()

['.ipynb_checkpoints',
 '540_ethans_python_class',
 '541_ethans_python_class',
 '602_ethans_python_class',
 '613_ethans_python_class',
 'Data Science',
 'my_database.db',
 'Projects',
 'SQL connection.ipynb',
 'Untitled Folder',
 'Untitled.ipynb']

In [5]:
import os

db_path = os.path.abspath("my_database.db")
db_path

"C:\\Users\\mayan\\Ethan's Python classes\\my_database.db"

In [6]:
# Create a cursor object
cursor = conn.cursor()

# Create a table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary INTEGER
)
""")

conn.commit()
print("Table created successfully")

Table created successfully

In [7]:
cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Rahul', 'Analytics', 80000)
""")

cursor.execute("""
INSERT INTO employees (name, department, salary)
VALUES ('Anita', 'Finance', 90000)
""")

conn.commit()
print("Data inserted")

Data inserted

In [8]:
#Insert using Pandas DataFrame

# Create sample DataFrame
df = pd.DataFrame({
    "name": ["Amit", "Neha", "Suresh"],
    "department": ["IT", "HR", "Marketing"],
    "salary": [70000, 65000, 72000]
})

# Insert DataFrame into SQLite table
df.to_sql("employees", conn, if_exists="append", index=False)

print("Data inserted via DataFrame")

Data inserted via DataFrame

In [10]:
query = "SELECT * FROM employees"

df_read = pd.read_sql(query, conn)
df_read

   id    name department  salary
0   1   Rahul  Analytics   80000
1   2   Anita    Finance   90000
2   3    Amit         IT   70000
3   4    Neha         HR   65000
4   5  Suresh  Marketing   72000
5   6   Rahul  Analytics   80000
6   7   Anita    Finance   90000
7   8    Amit         IT   70000
8   9    Neha         HR   65000
9  10  Suresh  Marketing   72000

In [11]:
conn.close()
print("Connection closed")

Connection closed

In [12]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp311-cp311-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/17.7 MB 2.4 MB/s eta 0:00:08
   -- ------------------------------------- 1.2/17.7 MB 13.1 MB/s eta 0:00:02
   ---- ----------------------------------- 2.1/17.7 MB 15.1 MB/s eta 0:00:02
   ------- -------------------------------- 3.4/17.7 MB 21.4 MB/s eta 0:00:01
   ------- -------------------------------- 3.4/17.7 MB 21.4 MB/s eta 0:00:01
   ------- -------------------------------- 3.4/17.7 MB 21.4 MB/s eta 0:00:01
   ------- -------------------------------- 3.4/17.7 MB 21.4 MB/s eta 0:00:01
   ------- -------------------------------- 3.4/17.7 MB 21.4 MB/s eta 0:00:01
   ------- -------------------------------- 3.4/17.7 MB 21.4 MB/s eta 0:00:01
   -------- ------------------------------- 3.6/17.7 MB 7.7 MB/s eta 0:00:02
   --------- ------------------------------ 4.3/17.7 MB 8.4 MB/s eta 0:00:02
   ----------- ---------------------------- 5.0/17.7 MB 9.2 MB/s eta 0:00:02
   ----------- ---------------------------- 5.0/17.7 MB 9.2 MB/s eta 0:00:02
   ----------- ---------------------------- 5.0/17.7 MB 9.2 MB/s eta 0:00:02
   ----------- ---------------------------- 5.0/17.7 MB 9.2 MB/s eta 0:00:02
   ----------- ---------------------------- 5.0/17.7 MB 9.2 MB/s eta 0:00:02
   ----------- ---------------------------- 5.0/17.7 MB 9.2 MB/s eta 0:00:02
   ------------ --------------------------- 5.4/17.7 MB 6.4 MB/s eta 0:00:02
   ------------- -------------------------- 5.8/17.7 MB 6.5 MB/s eta 0:00:02
   -------------- ------------------------- 6.5/17.7 MB 6.9 MB/s eta 0:00:02
   --------------- ------------------------ 6.9/17.7 MB 7.0 MB/s eta 0:00:02
   ---------------- ----------------------- 7.2/17.7 MB 7.0 MB/s eta 0:00:02
   ----------------- ---------------------- 7.6/17.7 MB 7.0 MB/s eta 0:00:02
   ----------------- ---------------------- 7.8/17.7 MB 6.9 MB/s eta 0:00:02
   ------------------ --------------------- 8.0/17.7 MB 6.8 MB/s eta 0:00:02
   ------------------ --------------------- 8.2/17.7 MB 6.7 MB/s eta 0:00:02
   ------------------ --------------------- 8.4/17.7 MB 6.6 MB/s eta 0:00:02
   ------------------- -------------------- 8.6/17.7 MB 6.5 MB/s eta 0:00:02
   ------------------- -------------------- 8.7/17.7 MB 6.4 MB/s eta 0:00:02
   -------------------- ------------------- 8.9/17.7 MB 6.3 MB/s eta 0:00:02
   -------------------- ------------------- 9.2/17.7 MB 6.3 MB/s eta 0:00:02
   --------------------- ------------------ 9.3/17.7 MB 6.2 MB/s eta 0:00:02
   --------------------- ------------------ 9.4/17.7 MB 6.1 MB/s eta 0:00:02
   --------------------- ------------------ 9.6/17.7 MB 6.0 MB/s eta 0:00:02
   ---------------------- ----------------- 9.7/17.7 MB 5.9 MB/s eta 0:00:02
   ---------------------- ----------------- 9.9/17.7 MB 5.9 MB/s eta 0:00:02
   ---------------------- ----------------- 10.0/17.7 MB 5.8 MB/s eta 0:00:02
   ----------------------- ---------------- 10.2/17.7 MB 5.7 MB/s eta 0:00:02
   ----------------------- ---------------- 10.4/17.7 MB 5.8 MB/s eta 0:00:02
   ----------------------- ---------------- 10.5/17.7 MB 5.6 MB/s eta 0:00:02
   ------------------------ --------------- 10.7/17.7 MB 5.6 MB/s eta 0:00:02
   ------------------------ --------------- 10.9/17.7 MB 5.4 MB/s eta 0:00:02
   ------------------------- -------------- 11.2/17.7 MB 5.3 MB/s eta 0:00:02
   ------------------------- -------------- 11.4/17.7 MB 5.2 MB/s eta 0:00:02
   -------------------------- ------------- 11.7/17.7 MB 5.1 MB/s eta 0:00:02
   --------------------------- ------------ 11.9/17.7 MB 5.0 MB/s eta 0:00:02
   --------------------------- ------------ 12.2/17.7 MB 4.9 MB/s eta 0:00:02
   ---------------------------- ----------- 12.5/17.7 MB 4.9 MB/s eta 0:00:02
   ---------------------------- ----------- 12.7/17.7 MB 4.7 MB/s eta 0:00:02
   ---------------------------- ----------- 12.8/17.7 MB 4.7 MB/s eta 0:00:02
   ----------------------------- ---------- 12.9/17.7 MB 4.6 MB/s eta 0:00:02
   ----------------------------- ---------- 13.0/17.7 MB 4.5 MB/s eta 0:00:02
   ----------------------------- ---------- 13.1/17.7 MB 4.4 MB/s eta 0:00:02
   ----------------------------- ---------- 13.2/17.7 MB 4.3 MB/s eta 0:00:02
   ------------------------------ --------- 13.4/17.7 MB 4.2 MB/s eta 0:00:02
   ------------------------------ --------- 13.6/17.7 MB 4.1 MB/s eta 0:00:01
   ------------------------------- -------- 13.7/17.7 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 13.9/17.7 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 14.1/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 14.3/17.7 MB 4.5 MB/s eta 0:00:01
   --------------------------------- ------ 14.6/17.7 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 14.9/17.7 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.7 MB 4.3 MB/s eta 0:00:01
   ----------------------------------- ---- 15.5/17.7 MB 4.7 MB/s eta 0:00:01
   ----------------------------------- ---- 15.8/17.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 16.2/17.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 16.4/17.7 MB 4.6 MB/s eta 0:00:01
   ------------------------------------- -- 16.7/17.7 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 17.2/17.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  17.4/17.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  17.5/17.7 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  17.7/17.7 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 4.2 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [15]:
import mysql.connector
import pandas as pd

In [19]:
conn = mysql.connector.connect(
    host="localhost",        # or 127.0.0.1
    user="root",             # your MySQL username
    password="Mayank12",# your MySQL password
    database="sakila"  # database you created in MySQL
)

print("Connected to MySQL successfully")

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [20]:
!pip uninstall mysql-connector-python -y
!pip install pymysql

Found existing installation: mysql-connector-python 26.7.0
Uninstalling mysql-connector-python-26.7.0:
  Successfully uninstalled mysql-connector-python-26.7.0
Requirement already satisfied: pymysql in c:\users\mayan\anaconda4\lib\site-packages (1.1.2)

In [21]:
import pymysql
import pandas as pd

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="Mayank@12",
    database="sakila",
    port=3306
)

print("Connected to MySQL successfully")

Connected to MySQL successfully

In [22]:
query = "SELECT * FROM actor"
df = pd.read_sql(query, conn)
df

C:\Users\mayan\AppData\Local\Temp\ipykernel_1940\832074063.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

     actor_id first_name     last_name         last_update
0           1   PENELOPE       GUINESS 2006-02-15 04:34:33
1           2       NICK      WAHLBERG 2006-02-15 04:34:33
2           3         ED         CHASE 2006-02-15 04:34:33
3           4   JENNIFER         DAVIS 2006-02-15 04:34:33
4           5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33
..        ...        ...           ...                 ...
195       196       BELA        WALKEN 2006-02-15 04:34:33
196       197      REESE          WEST 2006-02-15 04:34:33
197       198       MARY        KEITEL 2006-02-15 04:34:33
198       199      JULIA       FAWCETT 2006-02-15 04:34:33
199       200      THORA        TEMPLE 2006-02-15 04:34:33

[200 rows x 4 columns]